# Site settings
title:          tale of us
description:    "blabbery-blobber"
url:            "https://murlokito.github.io"


# Build settings
markdown:       kramdown
include:
  - _pages

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5

# Excludes
exclude: [ Gemfile, Gemfile.lock, tale.gemspec ]

theme:      tale

permalink:  /:year-:month-:day/:title
paginate:   5

github:
  repo: https://github.com/murlokito
